--sequences
CREATE SEQUENCE BSM.NOTIFICATIONS_SEQ AS INTEGER
      START WITH 1
      INCREMENT BY 1
      MAXVALUE 2147483647
      MINVALUE 1
      NO CYCLE
      NO CACHE
      NO ORDER;
    
GRANT USAGE, ALTER ON SEQUENCE BSM.NOTIFICATIONS_SEQ TO BSM_ROLE;

CREATE SEQUENCE BSM.USERCODE_SEQ AS INTEGER
      START WITH 1
      INCREMENT BY 1
      MAXVALUE 2147483647
      MINVALUE 1
      NO CYCLE
      NO CACHE
      NO ORDER;
     
GRANT USAGE, ALTER ON SEQUENCE BSM.USERCODE_SEQ TO BSM_ROLE;


--Common tables
CREATE TABLE BSM.ACCOUNTROLE  (
      USERCODE    INTEGER NOT NULL,
      ROLECODE    INTEGER NOT NULL,
      USERINSERT  VARCHAR(50) NOT NULL,
      TIMEINSERT  TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
      CONSTRAINT PK_ACCOUNTROLE PRIMARY KEY(USERCODE,ROLECODE)
)
IN BSM_TBSP
INDEX IN BSM_IX
COMPRESS YES
WITH RESTRICT ON DROP ;
 
GRANT SELECT,INSERT,UPDATE,DELETE,CONTROL,ALTER,INDEX,REFERENCES ON TABLE BSM.ACCOUNTROLE TO ROLE BSM_ROLE;
GRANT SELECT ON TABLE BSM.ACCOUNTROLE TO ROLE BSM_SELECT_ROLE;
 
CREATE TABLE BSM.APPLICATIONPARAMETER  (
      PARAMETERCODE     INTEGER NOT NULL,
      MAPPINGTYPE       SMALLINT NOT NULL,
      DESCRIPTION       VARCHAR(256),
      PARAMETERVALUE    DECIMAL(15,2),
      CATEGORY          INTEGER,
      FAILCODE          INTEGER,
      FAILMESSAGE       VARCHAR(256),
      VALUEFROM         BIGINT,
      VALUETO           BIGINT,
      ORDER             INTEGER,
      USERINSERT        VARCHAR(50) NOT NULL,
      TIMEINSERT        TIMESTAMP NOT NULL,
      USERUPDATE        VARCHAR(50),
      TIMEUPDATE        TIMESTAMP,
      CONSTRAINT PK_APPLICATIONPARAMETER PRIMARY KEY(PARAMETERCODE)
)
IN BSM_TBSP
INDEX IN BSM_IX
COMPRESS YES
WITH RESTRICT ON DROP ;
 
GRANT SELECT,INSERT,UPDATE,DELETE,CONTROL,ALTER,INDEX,REFERENCES ON TABLE BSM.APPLICATIONPARAMETER TO ROLE BSM_ROLE;
GRANT SELECT ON TABLE BSM.APPLICATIONPARAMETER TO ROLE BSM_SELECT_ROLE;
 
CREATE TABLE BSM.MSECLEVELDEFS  (
      ROLECODE   INTEGER NOT NULL,
      METHOD_NAME VARCHAR(75) NOT NULL,
      CLASS_ID   INTEGER NOT NULL,
      DESCRIPTION VARCHAR(150),
      ALLOW      SMALLINT DEFAULT 0,
      CR_DATE    TIMESTAMP DEFAULT CURRENT TIMESTAMP,
      ED_DATE    TIMESTAMP DEFAULT CURRENT TIMESTAMP,
      USERINSERT VARCHAR(50) NOT NULL,
      USERUPDATE VARCHAR(50) NOT NULL,
      CONSTRAINT PK_MSECLEVELDEFS PRIMARY KEY(ROLECODE,METHOD_NAME,CLASS_ID)
)
IN BSM_TBSP
INDEX IN BSM_IX
COMPRESS YES
WITH RESTRICT ON DROP ;
 
GRANT SELECT,INSERT,UPDATE,DELETE,CONTROL,ALTER,INDEX,REFERENCES ON TABLE BSM.MSECLEVELDEFS TO ROLE BSM_ROLE;
GRANT SELECT ON TABLE BSM.MSECLEVELDEFS TO ROLE BSM_SELECT_ROLE;
 
--ALTER TABLE BSM.NOTIFICATIONS DROP RESTRICT ON DROP ;
--DROP TABLE BSM.NOTIFICATIONS ;
CREATE TABLE BSM.NOTIFICATIONS  (
      ID                INTEGER NOT NULL,
      DISABLED          SMALLINT NOT NULL DEFAULT 0,
      DATE_FROM         DATE,
      DATE_TO           DATE,
      TITLE_LOCAL       VARCHAR(100),
      TITLE_EN          VARCHAR(50),
      MSG_LOCAL         VARCHAR(1000),
      MSG_EN            VARCHAR(500),
      DELAY_SECS        INTEGER NOT NULL DEFAULT 5,
      N_POSITION        INTEGER NOT NULL DEFAULT 8,
      CRM_CODE          INTEGER,
      USERNAMES         VARCHAR(1000),
      SHOW_IN_VIEWS     VARCHAR(5000),
      SEC_METHOD        VARCHAR(75),
      SEC_CLASS         VARCHAR(200),
      USERINSERT        VARCHAR(50) NOT NULL,
      TIMEINSERT        TIMESTAMP NOT NULL,
      USERUPDATE        VARCHAR(50),
      TIMEUPDATE        TIMESTAMP,
      CONSTRAINT PK_NOTIFICATIONS PRIMARY KEY(ID)
)
IN BSM_TBSP
INDEX IN BSM_IX
COMPRESS YES
WITH RESTRICT ON DROP ;
 
GRANT SELECT,INSERT,UPDATE,DELETE,CONTROL,ALTER,INDEX,REFERENCES ON TABLE BSM.NOTIFICATIONS TO ROLE BSM_ROLE;
GRANT SELECT ON TABLE BSM.NOTIFICATIONS TO ROLE BSM_SELECT_ROLE;
 
CREATE TABLE BSM.USER_LOG  (
      USER_NAME   VARCHAR(50) NOT NULL,
      RESULT      VARCHAR(200) NOT NULL,
      CR_DATE     TIMESTAMP DEFAULT CURRENT TIMESTAMP,
      BROWSER     VARCHAR(250) DEFAULT NULL,
      MAJOR       INTEGER DEFAULT NULL,
      MINOR       INTEGER DEFAULT NULL,
      ADDRESS     VARCHAR(50) DEFAULT NULL
)
IN BSM_TBSP
INDEX IN BSM_IX
COMPRESS YES
WITH RESTRICT ON DROP ;
 
GRANT SELECT,INSERT,UPDATE,DELETE,CONTROL,ALTER,INDEX,REFERENCES ON TABLE BSM.USER_LOG TO ROLE BSM_ROLE;
GRANT SELECT ON TABLE BSM.USER_LOG TO ROLE BSM_SELECT_ROLE;
 
CREATE TABLE BSM.TYPECLASS  (
      ID          INTEGER NOT NULL,
      CLASS_NAME  VARCHAR(200) NOT NULL,
      GRP         INTEGER NOT NULL,
      CR_DATE     TIMESTAMP DEFAULT CURRENT TIMESTAMP,
      USERINSERT  VARCHAR(50) NOT NULL,
      CONSTRAINT PK_TYPECLASS PRIMARY KEY(ID)
)
IN BSM_TBSP
INDEX IN BSM_IX
COMPRESS YES
WITH RESTRICT ON DROP ;
 
GRANT SELECT,INSERT,UPDATE,DELETE,CONTROL,ALTER,INDEX,REFERENCES ON TABLE BSM.TYPECLASS TO ROLE BSM_ROLE;
GRANT SELECT ON TABLE BSM.TYPECLASS TO ROLE BSM_SELECT_ROLE;
 
CREATE TABLE BSM.USERACCOUNT  (
      USERCODE    INTEGER NOT NULL,
      USERNAME    VARCHAR(50) NOT NULL,
      PASSWORD    VARCHAR(100) NULL,
      GUID        VARCHAR(120),
      LASTLOGIN   TIMESTAMP,
      USERINSERT  VARCHAR(50) NOT NULL,
      TIMEINSERT  TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
      USERUPDATE  VARCHAR(50) NOT NULL,
      TIMEUPDATE  TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
      CONSTRAINT PK_USERACCOUNT PRIMARY KEY(USERCODE)
)
IN BSM_TBSP
INDEX IN BSM_IX
COMPRESS YES
WITH RESTRICT ON DROP ;
 
GRANT SELECT,INSERT,UPDATE,DELETE,CONTROL,ALTER,INDEX,REFERENCES ON TABLE BSM.USERACCOUNT TO ROLE BSM_ROLE;
GRANT SELECT ON TABLE BSM.USERACCOUNT TO ROLE BSM_SELECT_ROLE;
 
CREATE TABLE BSM.USERROLE  (
      ROLECODE   INTEGER NOT NULL,
      ROLETYPE   INTEGER NOT NULL,
      DESCRIPTION VARCHAR(30) NOT NULL,
      USERINSERT VARCHAR(50) NOT NULL,
      TIMEINSERT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
      CONSTRAINT PK_USERROLE PRIMARY KEY(ROLECODE)
)
IN BSM_TBSP
INDEX IN BSM_IX
COMPRESS YES
WITH RESTRICT ON DROP ;
 
GRANT SELECT,INSERT,UPDATE,DELETE,CONTROL,ALTER,INDEX,REFERENCES ON TABLE BSM.USERROLE TO ROLE BSM_ROLE;
GRANT SELECT ON TABLE BSM.USERROLE TO ROLE BSM_SELECT_ROLE;
 
CREATE TABLE BSM.USERS  (
      USERCODE    INTEGER NOT NULL,
      GENDER      INTEGER,
      LASTNAME    VARCHAR(40) NOT NULL,
      FIRSTNAME   VARCHAR(20) NOT NULL,
      USERTYPE    INTEGER NULL,
      STATUSCODE  INTEGER NOT NULL,
      EMAIL       VARCHAR(180) NULL,
      MEMBERCODE  INTEGER,
      TELEPHONE   VARCHAR(120),
      POSITION    INTEGER NULL,
      USERINSERT  VARCHAR(50) NOT NULL,
      TIMEINSERT  TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
      USERUPDATE  VARCHAR(50) NOT NULL,
      TIMEUPDATE  TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
      CONSTRAINT PK_USERS PRIMARY KEY(USERCODE)
)
IN BSM_TBSP
INDEX IN BSM_IX
COMPRESS YES
WITH RESTRICT ON DROP ;
 
GRANT SELECT,INSERT,UPDATE,DELETE,CONTROL,ALTER,INDEX,REFERENCES ON TABLE BSM.USERS TO ROLE BSM_ROLE;
GRANT SELECT ON TABLE BSM.USERS TO ROLE BSM_SELECT_ROLE;
 
CREATE  TABLE BSM.APP_SESSIONS  (
    USER_CODE             INTEGER NOT NULL,
    ADDRESS              VARCHAR(50) NULL,
    TIMEINSERT            TIMESTAMP NOT NULL,
 
    CONSTRAINT PK_APP_SESSIONS PRIMARY KEY(USER_CODE)
)
IN BSM_TBSP
INDEX IN BSM_IX
COMPRESS YES
WITH RESTRICT ON DROP ;
 
GRANT SELECT,INSERT,UPDATE,DELETE,CONTROL,ALTER,INDEX,REFERENCES ON TABLE BSM.APP_SESSIONS TO ROLE BSM_ROLE;
GRANT SELECT ON TABLE BSM.APP_SESSIONS TO ROLE BSM_SELECT_ROLE;
 
CREATE  TABLE BSM.APP_LOCKS  (
    LOCK_TYPE                 INTEGER NOT NULL,
    LOCK_ITEM_ID            INTEGER NOT NULL,
    USER_CODE               INTEGER NOT NULL,
    TIMEINSERT              TIMESTAMP NOT NULL,
 
    CONSTRAINT PK_APP_LOCKS PRIMARY KEY(LOCK_TYPE, LOCK_ITEM_ID)
)
IN BSM_TBSP
INDEX IN BSM_IX
COMPRESS YES
WITH RESTRICT ON DROP ;

GRANT SELECT,INSERT,UPDATE,DELETE,CONTROL,ALTER,INDEX,REFERENCES ON TABLE BSM.APP_LOCKS TO ROLE BSM_ROLE;
GRANT SELECT ON TABLE BSM.APP_LOCKS TO ROLE BSM_SELECT_ROLE;

 
ALTER TABLE BSM.TYPECLASS
      ADD CONSTRAINT UNQ_CLASSNAME
      UNIQUE (CLASS_NAME, GRP);
 

ALTER TABLE BSM.USERACCOUNT
      ADD CONSTRAINT UNQ_USERNAME
      UNIQUE (USERNAME);


select * from bsm.users
select * from bsm.USERACCOUNT

delete from bsm.users;
delete from bsm.USERACCOUNT;