package com.tooooolazy.domain.objects;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AccountRoleId generated by hbm2java
 */
@Embeddable
public class AccountRoleId implements java.io.Serializable {

	@Column(name = "USERCODE", nullable = false)
	private int userCode;
	@Column(name = "ROLECODE", nullable = false)
	private int roleCode;

	public AccountRoleId() {
	}

	public AccountRoleId(int userCode, int roleCode) {
		this.userCode = userCode;
		this.roleCode = roleCode;
	}

	public int getUserCode() {
		return this.userCode;
	}

	public void setUserCode(int userCode) {
		this.userCode = userCode;
	}

	public int getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(int roleCode) {
		this.roleCode = roleCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccountRoleId))
			return false;
		AccountRoleId castOther = (AccountRoleId) other;

		return (this.getUserCode() == castOther.getUserCode())
				&& (this.getRoleCode() == castOther.getRoleCode());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserCode();
		result = 37 * result + this.getRoleCode();
		return result;
	}

}
